### ISSUE TITLE
Generate SystemlessDebloaterList.sh file

### ISSUE THREAD

**Issue by UnrealKaraulov** [Magisk-Modules-Alt-Repo/SystemlessDebloater#1]
Possible to add generation of SystemlessDebloaterList.sh to this module? (by installed apps)

**Comment by ipdev99** [comment]
I have an idea of how to create an example list from the current device.
_The current running system (rom)_.

You (the user) would still have to edit the config file to select what is debloated.
```
### Work-In-Progress to create a sample config script from the device.
# make_sample_config(){
# 	### find /system/app/ -type f | grep -o '[^/]*$' | sed 's/\.apk//g'; ## Started with this command. Improved with the following command.
#	### The updated command should return only the apk file name, and sorted into alphabetical order. Not sure if this will work with multiple calls.
#	### It will put each directory in order.. Not sure if run as a function what will happen.??
#	### More than likely have to push the output to a temp file, then sort and cat the temp file to an example config file.
#	find /system/app/ -type f | grep -o '[^/]*.apk$' | sed 's/\.apk//g' | sort;
# 	## find /system/priv-app/
# 	## find /vendor/app/
# 	## find /product/app/
# 	## find /product/priv-app/
# 	## find /data/app/
# 	## find /system/india/
# }
```
Cheers. :cowboy_hat_face:

**Comment by zgfg** [comment]
Thanks to your support, new version v1.5.1 was just released:
https://github.com/zgfg/SystemlessDebloater/releases/tag/151

---

Since v1.5.1, Systemless Debloater module supports your new SystemlessDebloater.cfg config file

Update will create this new config file and transfer your old DebloatList

Please delete then your old SystemlessDebloaterList.sh input file and read and use the new config file instead

---

For those who install the module first time, module will create that empty SystemlessDebloater.cfg config file (on Internal memory, Download folder)

Open the config file and read the instructions there

---

With this new config file, you can list but comment out certain apps:
Code, eg:

```
# My list of stock apps for debloating:
Velvet
# Chrome
YouTube
Mail
```

Hence, only Velvet (Google app), YouTube and Mail apps will be debloated

But if you uncomment Chrome (by removing hash sign # in front of the name), and reinstall the module - then all four apps will be debloated
